name: Enhancement
description: I want to suggest an improvement or new feature for Dynamic Views.
labels:
  - enhancement
body:
- type: checkboxes
  id: checklist
  attributes:
    label: Enhancement checklist
    options:
      - label: I have searched existing issues and this is not a duplicate
        required: true
      - label: I have updated to the latest version of Dynamic Views
        required: true
      - label: I have updated to the latest version of Obsidian
        required: true
- type: markdown
  attributes:
    value: "**Note:** If English is not your first language, please consider using AI tools like ChatGPT to translate your text."
- type: checkboxes
  id: affected-views
  attributes:
    label: What views does the issue affect? (If applicable)
    options:
      - label: Bases view
      - label: Datacore view
- type: textarea
  id: use-case
  attributes:
    label: Use case or problem
    description: What's your use case for this feature? In other words, what are you trying to accomplish when you realize you need this feature?
    placeholder: Describe use case or problem here...
  validations:
    required: true
- type: textarea
  id: proposed-solution
  attributes:
    label: Proposed solution
    description: The meat of the feature request. How do you think we should implement this feature and how would this solve your problem?
    placeholder: Describe solution here...
  validations:
    required: true
- type: textarea
  id: workaround
  attributes:
    label: Current workaround (optional)
    description: If you're using any workarounds, it might be helpful to us to get some inspiration.
    placeholder: Describe workaround here...
  validations:
    required: false
- type: textarea
  id: debug-info
  attributes:
    label: Debug information (optional)
    description: |-
      If you want, you can copy and paste Obsidian's Debug Information here:

      1. Open Command palette.
      2. Search for then select "Show debug info".
      3. Press "Copy to clipboard".
      4. Paste the copied text here.
    placeholder: Paste debug info here...
    render: text
  validations:
    required: false
- type: textarea
  id: plugin-settings
  attributes:
    label: Dynamic Views plugin settings (optional)
    description: |-
      To share your Dynamic Views plugin settings:

      1. Open your [configuration folder](https://help.obsidian.md/data-storage#Vault+settings).
      2. Navigate to `plugins/dynamic-views`.
      3. Copy `data.json`.
      4. Paste the copied file here.
    placeholder: If you want, you can paste your Dynamic Views plugin settings here...
    render: json
  validations:
    required: false
- type: textarea
  id: style-settings
  attributes:
    label: Style Settings configuration (optional)
    description: |-
      To share your Style Settings configuration:

      1. Open Style Settings.
      2. Press "Export settings" to the right of the Dynamic Views section.
      3. Paste the copied text here.
    placeholder: If you want, you can paste your Style Settings configuration here...
    render: json
  validations:
    required: false
- type: textarea
  id: additional-info
  attributes:
    label: Additional information (optional)
    description: Provide any additional information that you think would be helpful to understand your suggestion.
    placeholder: Provide additional information here...
  validations:
    required: false
