import { Settings, DefaultViewSettings } from "./types";

export const DEFAULT_VIEW_SETTINGS: DefaultViewSettings = {
  titleProperty: "file.name",
  textPreviewProperty: "",
  imageProperty: "",
  urlProperty: "url",
  propertyDisplay1: "file.tags",
  propertyDisplay2: "file.mtime",
  propertyDisplay3: "",
  propertyDisplay4: "",
  propertyDisplay5: "",
  propertyDisplay6: "",
  propertyDisplay7: "",
  propertyDisplay8: "",
  propertyDisplay9: "",
  propertyDisplay10: "",
  propertyDisplay11: "",
  propertyDisplay12: "",
  propertyDisplay13: "",
  propertyDisplay14: "",
  propertySet1SideBySide: true,
  propertySet2SideBySide: false,
  propertySet3SideBySide: false,
  propertySet4SideBySide: false,
  propertySet5SideBySide: false,
  propertySet6SideBySide: false,
  propertySet7SideBySide: false,
  propertySet1Position: "bottom",
  propertySet2Position: "bottom",
  propertySet3Position: "bottom",
  propertySet4Position: "bottom",
  propertySet5Position: "bottom",
  propertySet6Position: "bottom",
  propertySet7Position: "bottom",
  cssclasses: "",
  propertyLabels: "hide",
  subtitleProperty: "file.folder",
  fallbackToContent: true,
  fallbackToEmbeds: "always",
  imageFormat: "thumbnail-right",
  imageFit: "crop",
  imageAspectRatio: 1.0,
  queryHeight: 0,
  listMarker: "bullet",
  cardSize: 400,
};

export const DEFAULT_SETTINGS: Settings = {
  titleProperty: "file.name",
  textPreviewProperty: "",
  imageProperty: "",
  urlProperty: "url",
  omitFirstLine: "ifMatchesTitle",
  subtitleProperty: "file.folder",
  fallbackToContent: true,
  fallbackToEmbeds: "always",
  propertyDisplay1: "file.tags",
  propertyDisplay2: "file.mtime",
  propertyDisplay3: "",
  propertyDisplay4: "",
  propertyDisplay5: "",
  propertyDisplay6: "",
  propertyDisplay7: "",
  propertyDisplay8: "",
  propertyDisplay9: "",
  propertyDisplay10: "",
  propertyDisplay11: "",
  propertyDisplay12: "",
  propertyDisplay13: "",
  propertyDisplay14: "",
  propertySet1SideBySide: true,
  propertySet2SideBySide: false,
  propertySet3SideBySide: false,
  propertySet4SideBySide: false,
  propertySet5SideBySide: false,
  propertySet6SideBySide: false,
  propertySet7SideBySide: false,
  propertySet1Position: "bottom",
  propertySet2Position: "bottom",
  propertySet3Position: "bottom",
  propertySet4Position: "bottom",
  propertySet5Position: "bottom",
  propertySet6Position: "bottom",
  propertySet7Position: "bottom",
  cssclasses: "",
  propertyLabels: "hide",
  imageFormat: "thumbnail-right",
  imageFit: "crop",
  imageAspectRatio: 1.0,
  listMarker: "bullet",
  randomizeAction: "shuffle",
  queryHeight: 0,
  openFileAction: "card",
  openRandomInNewTab: true,
  smartTimestamp: true,
  createdTimeProperty: "created time",
  modifiedTimeProperty: "modified time",
  cardSize: 400,
  preventSidebarSwipe: "disabled",
  revealInNotebookNavigator: "disable",
  showYoutubeThumbnails: true,
  showCardLinkCovers: true,
};

export const DEFAULT_UI_STATE = {
  sortMethod: "mtime-desc",
  viewMode: "card",
  searchQuery: "",
  resultLimit: "",
  widthMode: "normal",
};

export const DEFAULT_TEMPLATE_VIEWS = {
  grid: null,
  masonry: null,
  list: null,
};

export const STORAGE_KEY_PREFIX = "dynamic-views";
