import { Settings, DefaultViewSettings } from "./types";

export const DEFAULT_VIEW_SETTINGS: DefaultViewSettings = {
  titleProperty: "",
  descriptionProperty: "",
  imageProperty: "",
  urlProperty: "",
  propertyDisplay1: "file.tags",
  propertyDisplay2: "",
  propertyDisplay3: "file.path",
  propertyDisplay4: "file.mtime",
  propertyDisplay5: "",
  propertyDisplay6: "",
  propertyDisplay7: "",
  propertyDisplay8: "",
  propertyDisplay9: "",
  propertyDisplay10: "",
  propertyDisplay11: "",
  propertyDisplay12: "",
  propertyDisplay13: "",
  propertyDisplay14: "",
  propertyLayout12SideBySide: false,
  propertyLayout34SideBySide: true,
  propertyLayout56SideBySide: false,
  propertyLayout78SideBySide: false,
  propertyLayout910SideBySide: false,
  propertyLayout1112SideBySide: false,
  propertyLayout1314SideBySide: false,
  propertyGroup1Position: "bottom",
  propertyGroup2Position: "bottom",
  propertyGroup3Position: "bottom",
  propertyGroup4Position: "bottom",
  propertyGroup5Position: "bottom",
  propertyGroup6Position: "bottom",
  propertyGroup7Position: "bottom",
  propertyLabels: "hide",
  showTitle: true,
  subtitleProperty: "",
  showTextPreview: true,
  fallbackToContent: true,
  fallbackToEmbeds: "always",
  imageFormat: "thumbnail-right",
  coverFitMode: "crop",
  imageAspectRatio: 1.0,
  queryHeight: 0,
  listMarker: "bullet",
  cardSize: 400,
};

export const DEFAULT_SETTINGS: Settings = {
  titleProperty: "",
  descriptionProperty: "",
  imageProperty: "",
  urlProperty: "",
  omitFirstLine: false,
  showTitle: true,
  subtitleProperty: "",
  showTextPreview: true,
  fallbackToContent: true,
  fallbackToEmbeds: "always",
  propertyDisplay1: "file.tags",
  propertyDisplay2: "",
  propertyDisplay3: "file.path",
  propertyDisplay4: "file.mtime",
  propertyDisplay5: "",
  propertyDisplay6: "",
  propertyDisplay7: "",
  propertyDisplay8: "",
  propertyDisplay9: "",
  propertyDisplay10: "",
  propertyDisplay11: "",
  propertyDisplay12: "",
  propertyDisplay13: "",
  propertyDisplay14: "",
  propertyLayout12SideBySide: false,
  propertyLayout34SideBySide: true,
  propertyLayout56SideBySide: false,
  propertyLayout78SideBySide: false,
  propertyLayout910SideBySide: false,
  propertyLayout1112SideBySide: false,
  propertyLayout1314SideBySide: false,
  propertyGroup1Position: "bottom",
  propertyGroup2Position: "bottom",
  propertyGroup3Position: "bottom",
  propertyGroup4Position: "bottom",
  propertyGroup5Position: "bottom",
  propertyGroup6Position: "bottom",
  propertyGroup7Position: "bottom",
  propertyLabels: "hide",
  imageFormat: "thumbnail-right",
  coverFitMode: "crop",
  imageAspectRatio: 1.0,
  timestampFormat: "",
  listMarker: "bullet",
  randomizeAction: "shuffle",
  thumbnailCacheSize: "balanced",
  queryHeight: 0,
  openFileAction: "card",
  openRandomInNewPane: true,
  showShuffleInRibbon: true,
  showRandomInRibbon: true,
  smartTimestamp: true,
  createdTimeProperty: "",
  modifiedTimeProperty: "",
  fallbackToFileMetadata: true,
  cardSize: 400,
};

export const DEFAULT_UI_STATE = {
  sortMethod: "mtime-desc",
  viewMode: "card",
  searchQuery: "",
  resultLimit: "",
  widthMode: "normal",
};

export const STORAGE_KEY_PREFIX = "dynamic-views";

export const CSS_CLASSES = {
  CONTAINER: "dynamic-views-container",
  GRID: "dynamic-views-grid",
  MASONRY: "dynamic-views-masonry",
  LIST: "dynamic-views-list",
  TOOLBAR: "dynamic-views-toolbar",
  SETTINGS: "dynamic-views-settings",
  CONTROL_BAR: "dynamic-views-control-bar",
};
